import { FastifyInstance } from 'fastify';
import * as fs from 'fs';
import * as path from 'path';

export async function apiDocsRoutes(server: FastifyInstance) {
  // Serve the comprehensive OpenAPI YAML spec
  server.get('/openapi.yaml', async (request, reply) => {
    const yamlPath = path.join(__dirname, '../../../../docs/api/openapi.yaml');

    if (!fs.existsSync(yamlPath)) {
      return reply.code(404).send({ error: 'OpenAPI specification not found' });
    }

    const yamlContent = fs.readFileSync(yamlPath, 'utf8');
    reply.header('Content-Type', 'application/x-yaml');
    return yamlContent;
  });

  // Serve OpenAPI JSON (auto-generated by Swagger)
  server.get('/openapi.json', async (request, reply) => {
    reply.redirect('/docs/json');
  });

  // Redirect /api-docs to /docs
  server.get('/api-docs', async (request, reply) => {
    reply.redirect('/docs');
  });
}
